import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  minHScreen: {
    flex: 1,
  },
  scrollView: {
    marginTop: 50,
    padding: 3,
    height: "50%",
  },
  productContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 5,
    backgroundColor: "white",
    borderRadius: 50,
    margin: 5,
  },
  productInnerContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    width: "100%",
    paddingHorizontal: 20,
  },
  productDetails: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    width: "35%",
    padding: 5,
  },
  titleContainer: {
    flex: 1,
    marginLeft: 20,
  },
  title: {
    fontSize: 14,
    lineHeight: 19,
    letterSpacing: 0,
    fontWeight: "500",
    fontFamily: "ManropeRegular",
    color: "#1E222B",
  },
  price: {
    fontSize: 14,
    lineHeight: 20,
    letterSpacing: 0,
    fontWeight: "400",
    fontFamily: "ManropeRegular",
    color: "#1E222B",
  },
  plusMinus: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    width: "30%",
    padding: 10,
  },
  plusminusBG: {
    width: 30,
    height: 30,
    borderRadius: 50,
    backgroundColor: "#F9F8FB",
    alignItems: "center",
    justifyContent: "center",
  },
  editButtonContainer: {
    flexDirection: "row",
    justifyContent: "flex-end",
    alignItems: "center",
    padding: 20,
  },
  edit: {
    fontSize: 16,
    lineHeight: 20,
    letterSpacing: 0,
    fontWeight: "500",
    fontFamily: "ManropeRegular",
    color: "#2A4BA0",
  },
  totalContainer: {
    backgroundColor: "#F8F9FB",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    height: "40%",
    padding: 20,
    marginLeft: 10,
    width: "95%",
  },
  totalDetails: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  gaptext: {
    marginVertical: 15,
  },
  gapamount: {
    marginVertical: 15,
    alignItems: "flex-end",
  },
  text: {
    marginBottom: 15,
    fontSize: 14,
    fontWeight: "400",
    lineHeight: 20,
    letterSpacing: 0,
    fontFamily: "ManropeRegular",
    color: "#616A7D",
  },
  amount: {
    marginBottom: 15,
    fontSize: 14,
    fontWeight: "500",
    lineHeight: 20,
    letterSpacing: 0,
    fontFamily: "ManropeRegular",
    color: "#1E222B",
  },
  buttonCheckout: {
    width: "100%",
    height: 56,
    bottom: 0,
    borderRadius: 20,
    backgroundColor: "#2A4BA0",
    justifyContent: "center",
    marginTop: 35,
  },
  buttonText: {
    fontSize: 16,
    fontWeight: "500",
    lineHeight: 20,
    letterSpacing: 0,
    fontFamily: "ManropeRegular",
    color: "#FFFFFF",
    textAlign: "center",
  },
});

export default styles;
